### ISSUE TITLE
dll version

### ISSUE THREAD

**Issue by dawoat** [jcageman/d2mapapi#8] opened 2021-11-16 11:44 UTC
Is it possible to put this in an dll to integrate it into a c# webservice?

**Comment by jcageman** [comment] 2021-11-16 17:21
That might be possible yes, I've tried it myself but failed so far. It's harder since you also need to load diablo dlls within that DLL and that didn't seem to work with diablo...

**Comment by scizzydo** [comment] 2021-12-02 19:54
I can confirm that it does work in a DLL. I'm not sure what you did jcageman in your tests that failed. I exported the functions I wanted from the dll with extern "C" to prevent name mangling and imported them from the endpoint application with the d2mapapi.dll and successfully created the collision map

**Comment by jcageman** [comment] 2021-12-02 20:08
That sounds very promising. I would definitely prefer a C# web application over the current C++ one. If you have something working i would be glad to take it over in this repository.

**Comment by dawoat** [comment] 2021-12-02 20:21
This would be very nice to build a C# Webapi around it. Can you provide the working dll?

**Comment by scizzydo** [comment] 2021-12-02 20:55
I'll make a branch for DLL I guess

**Comment by jcageman** [comment] 2021-12-02 21:15
If you give me that i can improve upon your branch further and give it a easier to use interface.

**Comment by scizzydo** [comment] 2021-12-03 07:01
https://github.com/scizzydo/d2mapapi is what I pushed, slimmed down with slight modifications. I tested on C# and C++ for DllImport with it. It's then up to the importing language to do what they want with the exported functions

**Comment by jcageman** [comment] 2021-12-04 12:19
@scizzydo 
Do you also have an example of the c# side? saves me some effort in building and testing those structures again in C# :)

**Comment by scizzydo** [comment] 2021-12-04 18:30
https://gist.github.com/scizzydo/0fc1bb9252f66f862ed1ab41d22b433f

**Comment by jcageman** [comment] 2021-12-05 13:00
Thanks, this helped me a ton. I've nearly finished rewriting everything into C# now (got a working API). I'll update this repository with the much easier to use C# Web API :)

**Comment by jcageman** [comment] 2021-12-05 13:40
If you guys want to test:
https://github.com/jcageman/d2mapapi/tree/netcoreversion
Still need to do quite some testing myself, but thought it make sense to already release and get some feedback.

**Comment by dawoat** [comment] 2021-12-05 14:48
Hi as first suggestion instead of specify the path in configsettings.
you could use it static:
HttpContext.Current.Request.PhysicalApplicationPath
or
HttpRuntime.AppDomainAppPath

and build it with Path.Combine(appPath, DiabloFolder)

I think in an Webservice you will have it in the Service RootFolder.

**Comment by dawoat** [comment] 2021-12-05 17:16
And i have another question:
Multiple client access? What i have in mind is that only one user at the same time could read from D2?
If it is like this there must be a queue to solve the tasks, otherwise we get a problem.
Iam right in this case?

**Comment by scizzydo** [comment] 2021-12-05 18:40
So, I didn't want export the RemoveRoomData. I noticed in your one you're adding the data twice where you'd normally remove. I didn't export it because I didn't think it would matter to remove as with different seeds it's different maps for that result, and I figured the unload act would take care of that. Just a thing I noticed.

**Comment by dawoat** [comment] 2021-12-06 13:47
we use the structure from d2mapapi (cmd server version) 

what i see is that the webapi didn't have the the same functionality.
when porting is done it would be fine touse the same structure and functionality as it was.
only without using the sessions. this would make port off existing application much easier.

**Comment by jcageman** [comment] 2021-12-06 17:18
> Hi as first suggestion instead of specify the path in configsettings. you could use it static:
> 
> 1. AppData from .NetCore
> 2. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0
> 
> (i tried to clone the repository... but get only the main branch) so i downloaded it

Had a look at it, but i don't see what this improves yet? With the current solution you can just point to your diablo 2 installation. In your proposal the diablo files need to be part of the wwwroot right?

> And i have another question: Multiple client access? What i have in mind is that only one user at the same time could read from D2? If it is like this there must be a queue to solve the tasks, otherwise we get a problem. Iam right in this case?

This cannot really be solved within this project i am afraid, best would be to just host multiple containers / web apps and put some load balancer in front to ensure not too many requests land on one instance. Due to the fact an instance can be quite small i think with containerizing this application you could achieve quite a lot. Adding queuing doesn't really help much in this case.

> So, I didn't want export the RemoveRoomData. I noticed in your one you're adding the data twice where you'd normally remove. I didn't export it because I didn't think it would matter to remove as with different seeds it's different maps for that result, and I figured the unload act would take care of that. Just a thing I noticed.

Ouch! good catch regarding RemoveRoomData, fixed that. I preferred to actually call it to prevent memory leaks.

> we use the structure from d2mapapi (cmd server version)
> 
> what i see is that the webapi didn't have the the same functionality. when porting is done it would be fine to use the same structure and functionality as it was. only without using the sessions. this would make port off existing application much easier -> only remove the sessions from existing code... and not implement all new...

Good point, i'll keep the map response the same for backwards compatibility purposes.

**Comment by jcageman** [comment] 2021-12-07 20:28
I've created a pull request at https://github.com/jcageman/d2mapapi/pull/12

I'll leave this open for a few days, so if you have any comments on it let me know in the pull request

**Comment by jcageman** [comment] 2021-12-11 11:05
PR has been merged!

**Closed by jcageman** 2021-12-11 11:05 UTC
